# ==========================================
# Application Properties
# ==========================================
spring.application.name=ECOMMERCE-GATEWAY
server.port=9999
spring.profiles.active=local


