# =============================
# JWT Configuration
# =============================
jwt.expiration=3600000
jwt.secret-key=VGhpc0lzQVNlY3VyZTI1NkJpdEtleUZvckpXVEhTMjU2ISE=
jwt.refresh-expiration=604800000


# ==========================================
# Route configuration
# ==========================================

# ============== USER-SERVICE ==============
spring.cloud.gateway.server.webflux.routes[0].id=USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri.=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1


# ============== AUTH-SERVICE ==============
spring.cloud.gateway.server.webflux.routes[1].id=AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[1].uri.=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1




