# ==========================================
# Application Properties
# ==========================================
spring.application.name=ECOMMERCE-GATEWAY
server.port=9999
spring.profiles.active=dev

# ==========================================
# Eureka Client Configuration
# ==========================================
eureka.client.service-url.default=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.client.registryFetchIntervalSeconds=5
eureka.instance.leaseRenewalIntervalInSeconds=10
eureka.instance.leaseExpirationDurationInSeconds=30

# ==========================================
# Actuator
# ==========================================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.export.enabled=true
management.tracing.sampling.probability=1.0

management.tracing.export.otlp.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces


management.otlp.metrics.export.enabled=false


spring.reactor.context-propagation=auto
