spring.application.name=USER-SERVICE
spring.profiles.active=dev
server.port=9092


# =============================
# Eureka Configuration
# =============================
eureka.client.service-url.default=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost

# =============================
# Actuator
# =============================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.export.enabled=true
management.tracing.sampling.probability=1.0


management.otlp.metrics.export.enabled=false
