pipeline {
    agent any

    options {
        disableConcurrentBuilds()
        timestamps()
    }

    environment {
        MODULE = 'auth-service'
    }

    stages {
        stage('debug') {
            steps {
                sh ' pwd'
            }
        }
    }
}