pipeline {
    agent any

    options {
        disableConcurrentBuilds()
        timestamps()
    }

    environment {
        MODULE = 'auth-service'
    }

    stages {

        stage('build utility-service') {
           dir('utility-service'){
           steps{
           sh 'mvn clean install'
           }
           }
        }

        stage('test') {
        dir('auth-service'){
            steps {
         sh 'mvn clean test'
        }
        }
    }
    }
}